name: ci
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: sync dependencies
        shell: bash
        run: |
          sudo apt-get update
          pip install -r requirements.txt
          python scripts.py sync-deps
      - name: configure
        shell: bash
        run: |
          python scripts.py configure
      - name: build
        shell: bash
        run: |
          make -C build -j 8